# Generated by Django 3.1.4 on 2020-12-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField()),
                ('id_in_source', models.IntegerField()),
                ('date', models.IntegerField()),
                ('exported', models.BooleanField()),
                ('size', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_profile_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('screen_name', models.CharField(max_length=100)),
                ('avatar_url', models.CharField(max_length=1000)),
                ('avatar_size', models.IntegerField()),
                ('source', models.CharField(max_length=100)),
            ],
        ),
    ]
