# Generated by Django 3.1.4 on 2020-12-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber_app', '0002_auto_20201229_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
