# Generated by Django 3.1.4 on 2020-12-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grabber_vk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkprofile',
            name='source_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
